language: python
sudo: enabled
dist: xenail
group: edge

python:
  - "3.5"

addons:
  chrome: stable
install:
  - echo $(google-chrome --version)
  - version=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE) &&
    wget -N "https://chromedriver.storage.googleapis.com/$version/chromedriver_linux64.zip" -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo apt-get install -y xvfb xclip
  - pip3 install -r $TRAVIS_BUILD_DIR/ui_testing/requirements.txt

script:
  - export TESTS='test09_my_profile.py:'
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export TESTS=''; fi
  #- echo $TESTS
  - cd $TRAVIS_BUILD_DIR && export PYTHONPATH='./'
  # - xvfb-run -a nosetests-3.4 -vs --nologcapture ui_testing/testcases/header_tests/$TESTS --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test05_testplans.py:TestPlansTestCases.test024_create_approach_overview_button_0_ok --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test05_testplans.py:TestPlansTestCases.test024_create_approach_overview_button_1_cancel --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test05_testplans.py:TestPlansTestCases.test025_edit_approach_overview_button --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test05_testplans.py:TestPlansTestCases.test026_testplans_search_then_navigate --tc-file=config.ini
  - xvfb-run -a nosetests-3.4 -vs --logging-level=WARNING ui_testing/testcases/basic_tests/test05_testplans.py:TestPlansTestCases.test027_hide_all_table_configurations --tc-file=config.ini


